In [1]:
import torch

In [10]:
x=torch.tensor(3.0, requires_grad=True)

In [11]:
y=x**2

In [12]:
y

tensor(9., grad_fn=<PowBackward0>)

In [15]:
y.backward() # y=x^2 right , toh backward se aapko milega derivative

In [16]:
print(x.grad)

tensor(6.)


In [19]:
import math
def dz_dx(x):
  return 2*x*math.cos(x**2)

In [20]:
dz_dx(3)

-5.466781571308061

In [21]:
x = torch.tensor(3.0,requires_grad=True)

In [22]:
y = x**2
z = torch.sin(y)

In [23]:
z.backward()

In [25]:
x.grad

tensor(-5.4668)

In [26]:
x = torch.tensor(6.7)
y = torch.tensor(0.0)

In [27]:
w=torch.tensor(1.0,requires_grad=True)

In [28]:
b=torch.tensor(0.0,requires_grad=True)

In [29]:
z= w*x+b

In [30]:
y_pred = torch.sigmoid(z)

In [35]:
loss = torch.binary_cross_entropy_with_logits(y_pred,y)

In [36]:
loss.backward()

In [37]:
print(w.grad,b.grad)

tensor(0.0060) tensor(0.0009)


As we see above it work with saclar wy better than expected , but it also work well with vector too

In [46]:
x = torch.tensor([1.0,2.0,3.0],requires_grad=True)

In [47]:
y= (x**2).mean()

In [48]:
 y.backward()

In [49]:
x.grad

tensor([0.6667, 1.3333, 2.0000])

Clearing grad

In [44]:
x=torch.tensor(2.0,requires_grad=True)

In [52]:
x.grad.zero_()

tensor([0., 0., 0.])

Disable gradient tracking

option 1 - requires_grad_(False)

option 2 - detach()

option 3 - torch.no_grad()

In [53]:
x.requires_grad_(False)

tensor([1., 2., 3.])

In [54]:
with torch.no_grad():
  y= x**2

In [55]:
y

tensor([1., 4., 9.])