In [1]:
import torch
print(torch.__version__)

2.6.0+cu124


In [2]:
if torch.cuda.is_available():
  print("GPU available")
  print(f"USING GPU:{torch.cuda.get_device_name(0)}")
else:
  print("GPU not avialable. Using CPU")

GPU available
USING GPU:Tesla T4


Creating a Tensor

In [3]:
torch.empty(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [4]:
#using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [5]:
#using rand
torch.rand(2,3)

tensor([[0.3708, 0.9649, 0.5696],
        [0.7283, 0.7242, 0.0967]])

In [6]:
#manual seed ( to make reproducibilty efficient)
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [7]:
# cutom tesnor
torch.tensor([[1,2,3,4],[5,6,7,8]])

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])

In [8]:
print("using arange", torch.arange(0,10,1))

using arange tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [9]:
print("using linspace",torch.linspace(0,10,10))

using linspace tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])


In [10]:
print("using eye",torch.eye(5))

using eye tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


In [11]:
print("torch.full",torch.full((4,4),4))

torch.full tensor([[4, 4, 4, 4],
        [4, 4, 4, 4],
        [4, 4, 4, 4],
        [4, 4, 4, 4]])


Tensor Shapes

In [12]:
x = torch.tensor([[1,2,3],[4,5,6]])

In [13]:
x.shape

torch.Size([2, 3])

In [14]:
torch.empty_like(x)

tensor([[135293888089488,       145999680,       146000544],
        [      145994784,               0,       146001440]])

In [15]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [16]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [17]:
torch.rand_like(x)

RuntimeError: "check_uniform_bounds" not implemented for 'Long'

in above code we are getting eorror why because , rand generate float values , & in x is tesnor conatining intergers , so we need to explicitly tell them that we need to generate float

**Tensor Data types**

In [18]:
x.dtype

torch.int64

In [19]:
#assign datatype when we are creating tesnor
print("assigning datatype", torch.tensor([[1.9999,2,7,3]],dtype=torch.int32))
print("assigning datatype", torch.tensor([[1.9999,2,7,3]],dtype=torch.float64))


assigning datatype tensor([[1, 2, 7, 3]], dtype=torch.int32)
assigning datatype tensor([[1.9999, 2.0000, 7.0000, 3.0000]], dtype=torch.float64)


In [20]:
#Using to()
x.to(torch.float8_e5m2fnuz)

tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float8_e5m2fnuz)

In [21]:
torch.rand_like(x,dtype=torch.float16)

tensor([[0.9609, 0.9424, 0.1709],
        [0.9629, 0.9229, 0.0259]], dtype=torch.float16)

Mathematical operations

In [22]:
x = torch.rand(2,2)
print(x)

tensor([[0.7118, 0.7876],
        [0.4183, 0.9014]])


In [23]:
print("Addition", x+2)
print("Subtraction", x-2)
print("Multiplication", x*2)
print("Addition", x/2)

Addition tensor([[2.7118, 2.7876],
        [2.4183, 2.9014]])
Subtraction tensor([[-1.2882, -1.2124],
        [-1.5817, -1.0986]])
Multiplication tensor([[1.4235, 1.5752],
        [0.8366, 1.8028]])
Addition tensor([[0.3559, 0.3938],
        [0.2092, 0.4507]])


In [24]:
print("mod", ((x+100)//3)%4)

mod tensor([[1., 1.],
        [1., 1.]])


In [25]:
a = torch.rand(3,4)
print("a",a)
b = torch.rand(3,4)
print("b",b)

a tensor([[0.9969, 0.7565, 0.2239, 0.3023],
        [0.1784, 0.8238, 0.5557, 0.9770],
        [0.4440, 0.9478, 0.7445, 0.4892]])
b tensor([[0.2426, 0.7003, 0.5277, 0.2472],
        [0.7909, 0.4235, 0.0169, 0.2209],
        [0.9535, 0.7064, 0.1629, 0.8902]])


In [26]:
print("Addition", a+b)
print("Subtraction", a-b)
print("Multiplication", a*b)
print("Division", a/b)

Addition tensor([[1.2394, 1.4569, 0.7516, 0.5495],
        [0.9693, 1.2473, 0.5726, 1.1979],
        [1.3976, 1.6542, 0.9074, 1.3794]])
Subtraction tensor([[ 0.7543,  0.0562, -0.3038,  0.0552],
        [-0.6125,  0.4004,  0.5388,  0.7561],
        [-0.5095,  0.2414,  0.5816, -0.4010]])
Multiplication tensor([[0.2418, 0.5298, 0.1181, 0.0747],
        [0.1411, 0.3489, 0.0094, 0.2158],
        [0.4234, 0.6696, 0.1213, 0.4355]])
Division tensor([[ 4.1099,  1.0802,  0.4243,  1.2232],
        [ 0.2256,  1.9454, 32.8859,  4.4230],
        [ 0.4657,  1.3418,  4.5708,  0.5495]])


In [27]:
print("mod", ((a+100)//3)%b)

mod tensor([[0.0120, 0.0840, 0.2833, 0.1246],
        [0.5737, 0.3915, 0.0128, 0.0867],
        [0.5798, 0.5055, 0.0986, 0.0627]])


In [28]:
c = torch.tensor([1,-2,3,-4])

In [29]:
#abs
torch.abs(c)

tensor([1, 2, 3, 4])

In [30]:
torch.neg(c)

tensor([-1,  2, -3,  4])

In [31]:
c = torch.tensor([1.7,-2.6,3.34,-04.67])

In [32]:
torch.round(c)

tensor([ 2., -3.,  3., -5.])

In [33]:
print("c",c)
print("floor",torch.floor(c))
print("Ceil",torch.ceil(c))

c tensor([ 1.7000, -2.6000,  3.3400, -4.6700])
floor tensor([ 1., -3.,  3., -5.])
Ceil tensor([ 2., -2.,  4., -4.])


In [34]:
#clamp
torch.clamp(c,min=2,max=3)

tensor([2., 2., 3., 2.])

**Reduction operations**

In [35]:
e = torch.randint(size=(2,3),low=0,high=10)

In [36]:
print("e",e)
print(torch.sum(e))
print(torch.sum(e,dim=1))
print(torch.sum(e,dim=0))


e tensor([[5, 7, 5],
        [9, 9, 7]])
tensor(42)
tensor([17, 25])
tensor([14, 16, 12])


In [37]:
e.to(torch.float32)


tensor([[5., 7., 5.],
        [9., 9., 7.]])

In [38]:
torch.mean(e)
print(torch.mean(e,dim=1))
print(torch.mean(e,dim=0))

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [39]:
torch.median(e)

tensor(7)

In [40]:
print("max",torch.max(e))
print('min',torch.min(e))

max tensor(9)
min tensor(5)


In [41]:
torch.std(e)

RuntimeError: std and var only support floating point and complex dtypes

In [42]:
torch.var(e)

RuntimeError: std and var only support floating point and complex dtypes

In [43]:
torch.argmax(e) #sabse bade wale no ki position batata hai

tensor(3)

In [44]:
torch.argmin(e)

tensor(0)

**Matrix Operation**

In [45]:
f= torch.randint(size=(2,3),low=0,high=10)
g= torch.randint(size=(3,2),low=0,high=10)

In [46]:
torch.matmul(f,g)

tensor([[137, 117],
        [139, 130]])

In [47]:
t= torch.tensor([1,2])
r= torch.tensor([10,32])

In [48]:
torch.dot(t,r)

tensor(74)

In [49]:
torch.transpose(f,0,1)

tensor([[5, 9],
        [9, 7],
        [8, 9]])

In [50]:
fq= torch.randint(size=(444,444),low=0,high=10,dtype=torch.float32)
torch.det(fq)

tensor(inf)

**Comparison Opertions**


In [51]:
i= torch.randint(size=(4,4),low=0,high=10,dtype=torch.float32)
j= torch.randint(size=(4,4),low=0,high=10,dtype=torch.float32)


In [52]:
print(i<j)
print(i>j)
print(i==j)
print(i>=j)
print(i!=j)

tensor([[ True,  True, False, False],
        [ True, False, False, False],
        [False,  True, False, False],
        [False,  True,  True,  True]])
tensor([[False, False,  True,  True],
        [False, False,  True, False],
        [ True, False,  True,  True],
        [False, False, False, False]])
tensor([[False, False, False, False],
        [False,  True, False,  True],
        [False, False, False, False],
        [ True, False, False, False]])
tensor([[False, False,  True,  True],
        [False,  True,  True,  True],
        [ True, False,  True,  True],
        [ True, False, False, False]])
tensor([[ True,  True,  True,  True],
        [ True, False,  True, False],
        [ True,  True,  True,  True],
        [False,  True,  True,  True]])


**Special functions**

In [53]:
k= torch.randint(size=(4,4),low=0,high=10,dtype=torch.float32)


In [54]:
print(torch.log(k))
print(torch.exp(k))
print(torch.sqrt(k))
print(torch.sigmoid(k))

tensor([[  -inf, 1.7918, 0.0000, 1.6094],
        [2.1972, 0.0000, 1.6094, 2.0794],
        [1.7918, 2.0794,   -inf, 0.6931],
        [2.1972, 1.9459, 2.1972, 1.7918]])
tensor([[1.0000e+00, 4.0343e+02, 2.7183e+00, 1.4841e+02],
        [8.1031e+03, 2.7183e+00, 1.4841e+02, 2.9810e+03],
        [4.0343e+02, 2.9810e+03, 1.0000e+00, 7.3891e+00],
        [8.1031e+03, 1.0966e+03, 8.1031e+03, 4.0343e+02]])
tensor([[0.0000, 2.4495, 1.0000, 2.2361],
        [3.0000, 1.0000, 2.2361, 2.8284],
        [2.4495, 2.8284, 0.0000, 1.4142],
        [3.0000, 2.6458, 3.0000, 2.4495]])
tensor([[0.5000, 0.9975, 0.7311, 0.9933],
        [0.9999, 0.7311, 0.9933, 0.9997],
        [0.9975, 0.9997, 0.5000, 0.8808],
        [0.9999, 0.9991, 0.9999, 0.9975]])


In [55]:
print(torch.relu(k))
print(torch.softmax(k,dim=0))

tensor([[0., 6., 1., 5.],
        [9., 1., 5., 8.],
        [6., 8., 0., 2.],
        [9., 7., 9., 6.]])
tensor([[6.0203e-05, 8.9976e-02, 3.2928e-04, 4.1922e-02],
        [4.8783e-01, 6.0625e-04, 1.7978e-02, 8.4203e-01],
        [2.4287e-02, 6.6484e-01, 1.2114e-04, 2.0872e-03],
        [4.8783e-01, 2.4458e-01, 9.8157e-01, 1.1396e-01]])


Inplace operations

In [56]:
m=torch.rand(2,3)
n=torch.rand(2,3)

In [57]:
m.add_(n)

tensor([[0.8560, 0.7409, 0.9248],
        [0.5869, 0.7821, 0.4449]])

In [58]:
n.relu_()

tensor([[0.5390, 0.1990, 0.2894],
        [0.5733, 0.6200, 0.3509]])

pandas ne bahoot accha design kar rakha hai _ lagado woh inplace operation ban jata hai


**Copying tensors**

In [59]:
a= torch.rand(2,3)

In [60]:
b=a

In [61]:
b

tensor([[0.2032, 0.3958, 0.4779],
        [0.3572, 0.2234, 0.8097]])

In [62]:
a[0][0]=0

In [63]:
b

tensor([[0.0000, 0.3958, 0.4779],
        [0.3572, 0.2234, 0.8097]])

yeh bahoot galat bat hai , 1 nayi copy banayi , toh jo changes copy me karte ja raha woh original me bhi hoti ja rahi hai

In [64]:
print(id(a))
print(id(b))

135289463618064
135289463618064


In [65]:
b = a.clone()


In [66]:
b= a.clone()

In [67]:
id(b)

135289463084272

**Tensor Operation on GPU**

In [68]:
torch.cuda.is_available()

True

In [69]:
device= torch.device('cuda')

In [70]:
torch.rand((2,3),device = device)

tensor([[0.3563, 0.0303, 0.7088],
        [0.2009, 0.0224, 0.9896]], device='cuda:0')

In [73]:
a= torch.rand(2,3)

In [74]:
a

tensor([[0.6981, 0.2981, 0.9378],
        [0.9431, 0.7146, 0.0233]])

In [75]:
b=a.to(device)

In [76]:
b

tensor([[0.6981, 0.2981, 0.9378],
        [0.9431, 0.7146, 0.0233]], device='cuda:0')

Reshaping Tesnors

In [77]:
#reshape
a= torch.ones(4,4)

In [81]:
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [82]:
#flaatten
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [84]:
#permute
b= torch.rand(2,3,4)
b.permute(2,0,1).shape

torch.Size([4, 2, 3])

In [85]:
#unsqueeze
c=torch.rand(226,226,3)
c.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])

In [86]:
c=torch.rand(226,226,3)
c.squeeze(0).shape

torch.Size([226, 226, 3])

NUMPY and Torch

In [87]:
import numpy as np

In [88]:
a= torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [89]:
b = a.numpy()

In [90]:
type(b)

numpy.ndarray

In [91]:
c = np.array([1,2,3])
c

array([1, 2, 3])

In [92]:
torch.from_numpy(c)

tensor([1, 2, 3])