In [1]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv("https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv")

In [3]:
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,fractal_dimension_mean,radius_se,texture_se,perimeter_se,area_se,smoothness_se,compactness_se,concavity_se,concave points_se,symmetry_se,fractal_dimension_se,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,1.0950,0.9053,8.589,153.40,0.006399,0.04904,0.05373,0.01587,0.03003,0.006193,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,0.5435,0.7339,3.398,74.08,0.005225,0.01308,0.01860,0.01340,0.01389,0.003532,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,0.05999,0.7456,0.7869,4.585,94.03,0.006150,0.04006,0.03832,0.02058,0.02250,0.004571,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,0.09744,0.4956,1.1560,3.445,27.23,0.009110,0.07458,0.05661,0.01867,0.05963,0.009208,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,0.05883,0.7572,0.7813,5.438,94.44,0.011490,0.02461,0.05688,0.01885,0.01756,0.005115,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN


In [4]:
df.shape

(569, 33)

train test split

In [19]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:,0]
, test_size=0.2)

Scaling

In [17]:
df.drop(columns=['id','Unnamed: 32'],inplace=True)

In [20]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [21]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [22]:
y_train

array([0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1,
       1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1,

In [23]:
X_train_tensor  = torch.from_numpy(X_train)
X_test_tensor  =torch.from_numpy(X_test)
y_train_tensor  = torch.from_numpy(y_train)
y_test_tensor  = torch.from_numpy(y_test)

In [43]:
class MysimpleNN():
  def __init__(self, X):
    self.weights = torch.rand(X.shape[1],1,dtype=torch.float64, requires_grad=True)
    self.bias = torch.zeros(1,dtype=torch.float64, requires_grad= True)

  def forward(self, X):
    z = torch.matmul(X, self.weights) + self.bias
    y_pred = torch.sigmoid(z)
    return y_pred

  def loss_function(self, y_pred, y):
    # Clamp prediction to avoid log(0)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

    # Calculate loss
    loss = -(y_train_tensor*torch.log(y_pred)+(1-y_train_tensor)*torch.log(1-y_pred)).mean()
    return loss









In [44]:
learning_rate = 0.1
epochs = 25

In [45]:
# create Model
model = MysimpleNN(X_train_tensor)
model.weights

tensor([[0.6425],
        [0.2779],
        [0.8666],
        [0.2218],
        [0.9820],
        [0.5913],
        [0.4163],
        [0.4012],
        [0.2800],
        [0.4100],
        [0.2630],
        [0.2359],
        [0.8671],
        [0.2319],
        [0.4269],
        [0.4030],
        [0.2311],
        [0.8052],
        [0.9948],
        [0.7607],
        [0.4675],
        [0.2845],
        [0.8347],
        [0.4147],
        [0.2391],
        [0.4049],
        [0.4878],
        [0.5857],
        [0.8933],
        [0.2797]], dtype=torch.float64, requires_grad=True)

In [46]:
model.bias

tensor([0.], dtype=torch.float64, requires_grad=True)

In [47]:
# forward pass
# loss calculate
# backward Pass
# parameters update

In [52]:
# create model
model = MysimpleNN(X_train_tensor)
#define loop
for epoch in range(epochs):
  # forward pass
  y_pred = model.forward(X_train_tensor)
  print(y_pred)

# loss calculate
  loss = model.loss_function(y_pred, y_train_tensor)
  print(f'Epoch:{epoch}, Loss:{loss.item()}')

# backward pass
  loss.backward()

  # parameters Update
  with torch.no_grad():
    model.weights -=learning_rate*model.weights.grad
    model.bias -=learning_rate*model.bias.grad
  #zero gradients

  model.weights.grad.zero_()
  model.bias.grad.zero_()
  print(f'Epoch:{epoch}, Loss:{loss.item()}')


Streaming output truncated to the last 5000 lines.
        [8.8335e-04],
        [6.4884e-02],
        [9.7327e-01],
        [1.0192e-02],
        [9.8452e-01],
        [2.1957e-01],
        [8.6669e-02],
        [9.8655e-01],
        [3.1816e-01],
        [1.1039e-02],
        [1.4733e-03],
        [6.3592e-02],
        [4.5469e-02],
        [6.4169e-01],
        [9.8335e-01],
        [9.8950e-01],
        [8.3915e-01],
        [1.0566e-01],
        [1.4321e-02],
        [3.7998e-02],
        [4.8556e-03],
        [9.8303e-01],
        [1.8382e-02],
        [9.5119e-01],
        [1.8190e-02],
        [9.1618e-01],
        [2.5054e-01],
        [8.9692e-01],
        [6.4078e-01],
        [5.4897e-01],
        [9.8919e-01],
        [1.5361e-01],
        [3.4797e-02],
        [6.7225e-03],
        [1.5366e-02],
        [2.5313e-01],
        [9.9926e-01],
        [1.3553e-01],
        [5.6629e-01],
        [4.2655e-01],
        [7.9430e-02],
        [5.1391e-01],
        [9.3002e-01],
   

In [53]:
model.weights

tensor([[-0.1136],
        [ 0.1555],
        [ 0.4113],
        [ 0.4639],
        [-0.0168],
        [-0.4969],
        [ 0.3230],
        [-0.5597],
        [ 0.0224],
        [ 0.3786],
        [ 0.2759],
        [ 0.3098],
        [-0.0384],
        [ 0.1639],
        [ 0.4668],
        [-0.4469],
        [ 0.0867],
        [ 0.3847],
        [ 0.1163],
        [ 0.4356],
        [ 0.1478],
        [ 0.2469],
        [ 0.0770],
        [-0.1835],
        [ 0.4627],
        [-0.4755],
        [ 0.0866],
        [-0.5498],
        [ 0.5609],
        [-0.1023]], dtype=torch.float64, requires_grad=True)

In [54]:
model.bias

tensor([-0.1139], dtype=torch.float64, requires_grad=True)

Evaluation

In [58]:
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred >0.5).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy : { accuracy.item()}')

Accuracy : 0.5261619091033936


In [56]:
print(y_pred)

tensor([[0.2512],
        [0.1541],
        [0.9586],
        [0.6443],
        [0.1884],
        [0.1797],
        [0.2880],
        [0.4858],
        [0.1067],
        [0.6409],
        [0.4566],
        [0.7249],
        [0.6371],
        [0.2527],
        [0.9349],
        [0.3720],
        [0.6316],
        [0.6237],
        [0.5374],
        [0.9416],
        [0.2255],
        [0.8387],
        [0.5299],
        [0.8116],
        [0.6993],
        [0.5613],
        [0.1263],
        [0.9278],
        [0.2228],
        [0.2081],
        [0.4147],
        [0.5923],
        [0.6763],
        [0.5191],
        [0.1063],
        [0.4553],
        [0.1975],
        [0.5139],
        [0.4760],
        [0.5566],
        [0.1733],
        [0.8343],
        [0.4026],
        [0.4794],
        [0.1741],
        [0.5803],
        [0.8586],
        [0.1504],
        [0.2982],
        [0.2226],
        [0.2116],
        [0.6584],
        [0.3181],
        [0.2481],
        [0.7019],
        [0