In [34]:
import numpy as np
import pandas as pd

In [35]:
df = pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]],columns=['cgpa','profile_score','lpa'])

In [36]:
df

cgpa  profile_score  lpa
0     8              8    4
1     7              9    5
2     6             10    6
3     5             12    7

In [37]:
def initialize_parameters(layer_dims):
  np.random.seed(3)
  parameters = {}
  L = len(layer_dims)

  for l in range(1,L):
    parameters['W'+str(l)] = np.ones((layer_dims[l-1],layer_dims[l]))*0.1
    parameters['b'+str(l)] = np.zeros((layer_dims[l],1))
  return parameters


In [38]:
initialize_parameters([2,2,1])

{'W1': array([[0.1, 0.1],
        [0.1, 0.1]]),
 'b1': array([[0.],
        [0.]]),
 'W2': array([[0.1],
        [0.1]]),
 'b2': array([[0.]])}

In [39]:
def linear_forward(A_prev, W,b):
  z = np.dot(W.T,A_prev)+b
  return z

In [54]:
# Forward Prop
def L_layer_forward(X,parameters):
  A = X
  L = len(parameters) // 2
  for l in range(1,L+1):
    A_prev = A
    w1 = parameters['W'+str(1)]
    b1 = parameters['b'+str(1)]
    #print("A"+str(l-1)+": ",A_prev)
    #print("W"+str(l-1)+": ",w1)
    #print("b"+str(l)+": ",b1)
    #print("__"*20)

    A = linear_forward(A_prev,w1,b1)
    ##print("A"+str(l)+": ",A)
    #print("++"*20)
  return A,A_prev


In [41]:
X = df[['cgpa','profile_score']].values[0].reshape(2,1)
y = df[['lpa']].values[0][0]

parameters = initialize_parameters([2,2,1])
y_hat,A1 = L_layer_forward(X,parameters)

A0:  [[8]
 [8]]
W0:  [[0.1 0.1]
 [0.1 0.1]]
b1:  [[0.]
 [0.]]
________________________________________
A1:  [[1.6]
 [1.6]]
++++++++++++++++++++++++++++++++++++++++
A1:  [[1.6]
 [1.6]]
W1:  [[0.1 0.1]
 [0.1 0.1]]
b2:  [[0.]
 [0.]]
________________________________________
A2:  [[0.32]
 [0.32]]
++++++++++++++++++++++++++++++++++++++++


In [42]:
print(y_hat,A1)

[[0.32]
 [0.32]] [[1.6]
 [1.6]]


In [43]:
def update_parameters(parameters,y,y_hat,A1,X):
  parameters['W2'][0][0] = parameters['W2'][0][0] + (0.001 * 2 * (y - y_hat)*A1[0][0])
  parameters['W2'][1][0] = parameters['W2'][1][0] + (0.001 * 2 * (y - y_hat)*A1[1][0])
  parameters['b2'][0][0] = parameters['W2'][1][0] + (0.001 * 2 * (y - y_hat))

  parameters['W1'][0][0] = parameters['W1'][0][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][0][0]*X[0][0])
  parameters['W1'][0][1] = parameters['W1'][0][1] + (0.001 * 2 * (y - y_hat)*parameters['W2'][0][0]*X[1][0])
  parameters['b1'][0][0] = parameters['b1'][0][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][0][0])

  parameters['W1'][1][0] = parameters['W1'][1][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][1][0]*X[0][0])
  parameters['W1'][1][1] = parameters['W1'][1][1] + (0.001 * 2 * (y - y_hat)*parameters['W2'][1][0]*X[1][0])
  parameters['b1'][1][0] = parameters['b1'][1][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][1][0])

In [45]:
y_hat = y_hat[0][0]

In [46]:
update_parameters(parameters,y,y_hat,A1,X)

In [47]:
parameters

{'W1': array([[0.10658137, 0.10658137],
        [0.10658137, 0.10658137]]),
 'b1': array([[0.00082267],
        [0.00082267]]),
 'W2': array([[0.111776],
        [0.111776]]),
 'b2': array([[0.119136]])}

In [48]:
X = df[['cgpa', 'profile_score']].values[3].reshape(2,1) # Shape(no of features, no. of training example)
y = df[['lpa']].values[3][0]

y_hat,A1 = L_layer_forward(X, parameters)

A0:  [[ 5]
 [12]]
W0:  [[0.10658137 0.10658137]
 [0.10658137 0.10658137]]
b1:  [[0.00082267]
 [0.00082267]]
________________________________________
A1:  [[1.81270598]
 [1.81270598]]
++++++++++++++++++++++++++++++++++++++++
A1:  [[1.81270598]
 [1.81270598]]
W1:  [[0.10658137 0.10658137]
 [0.10658137 0.10658137]]
b2:  [[0.00082267]
 [0.00082267]]
________________________________________
A2:  [[0.38722405]
 [0.38722405]]
++++++++++++++++++++++++++++++++++++++++


In [49]:
y_hat = y_hat[0][0]

In [50]:
update_parameters(parameters,y,y_hat,A1,X)

In [51]:

parameters

{'W1': array([[0.11555822, 0.1281258 ],
        [0.11555822, 0.1281258 ]]),
 'b1': array([[0.00261804],
        [0.00261804]]),
 'W2': array([[0.13575004],
        [0.13575004]]),
 'b2': array([[0.14897559]])}

In [57]:
parameters = initialize_parameters([2,2,1])
epochs = 5

for i in range(epochs):

  Loss = []

  for j in range(df.shape[0]):

    X = df[['cgpa', 'profile_score']].values[j].reshape(2,1) # Shape(no of features, no. of training example)
    y = df[['lpa']].values[j][0]

    # Parameter initialization


    y_hat,A1 = L_layer_forward(X,parameters)
    y_hat = y_hat[0][0]

    update_parameters(parameters,y,y_hat,A1,X)

    Loss.append((y-y_hat)**2)

  print('Epoch - ',i+1,'Loss - ',np.array(Loss).mean())

parameters

Epoch -  1 Loss -  26.907550899777384
Epoch -  2 Loss -  22.3318726301909
Epoch -  3 Loss -  14.694435066287255
Epoch -  4 Loss -  6.638049183540845
Epoch -  5 Loss -  2.2891135753499636


{'W1': array([[0.33329713, 0.49495871],
        [0.35907058, 0.54086843]]),
 'b1': array([[0.03836736],
        [0.04272922]]),
 'W2': array([[0.52455618],
        [0.64075209]]),
 'b2': array([[0.64511188]])}

Now using Keras


In [59]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [62]:
model = Sequential()
model.add(Dense(2,activation='linear',input_dim=2))
model.add(Dense(1,activation='linear'))

In [63]:
model.get_weights()

[array([[-0.9085074 , -1.142374  ],
        [ 0.28557003, -0.84104645]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[-0.01320207],
        [-0.38490963]], dtype=float32),
 array([0.], dtype=float32)]

In [64]:
new_weights = [np.array([[0.1, 0.1],
                         [0.1, 0.1 ]], dtype=np.float32),
np.array([0, 0.], dtype=np. float32),
np.array([[0.1], [0.1]], dtype=np.float32),
np.array([0.], dtype=np.float32)]

In [65]:
model.set_weights(new_weights)

In [66]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [67]:
optimizer = keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss='mean_squared_error',optimizer=optimizer)

In [69]:
model.fit(df.iloc[:,0:-1].values,df['lpa'].values,epochs=75,verbose=1,batch_size=1)

Epoch 1/75
4/4 [==============================] - 1s 7ms/step - loss: 27.8902
Epoch 2/75
4/4 [==============================] - 0s 4ms/step - loss: 27.5691
Epoch 3/75
4/4 [==============================] - 0s 5ms/step - loss: 27.2304
Epoch 4/75
4/4 [==============================] - 0s 6ms/step - loss: 26.9254
Epoch 5/75
4/4 [==============================] - 0s 5ms/step - loss: 26.5392
Epoch 6/75
4/4 [==============================] - 0s 4ms/step - loss: 26.2163
Epoch 7/75
4/4 [==============================] - 0s 3ms/step - loss: 25.8067
Epoch 8/75
4/4 [==============================] - 0s 4ms/step - loss: 25.4574
Epoch 9/75
4/4 [==============================] - 0s 3ms/step - loss: 25.0491
Epoch 10/75
4/4 [==============================] - 0s 3ms/step - loss: 24.6410
Epoch 11/75
4/4 [==============================] - 0s 4ms/step - loss: 24.2126
Epoch 12/75
4/4 [==============================] - 0s 4ms/step - loss: 23.8171
Epoch 13/75
4/4 [==============================] - 0s 4ms/ste

In [71]:
model.get_weights()

[array([[0.37370887, 0.37370887],
        [0.36586946, 0.36586946]], dtype=float32),
 array([0.2724992, 0.2724992], dtype=float32),
 array([[0.3731212],
        [0.3731212]], dtype=float32),
 array([0.20495439], dtype=float32)]