In [33]:
from keras import Sequential
from keras.layers import Dense, SimpleRNN
model= Sequential()

In [34]:
model.add(SimpleRNN(3,input_shape =(4,5))) # 4 no of words , 5no of vocab
model.add(Dense(1,activation="sigmoid"))
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn_1 (SimpleRNN)    (None, 3)                 27        
                                                                 
 dense_1 (Dense)             (None, 1)                 4         
                                                                 
Total params: 31 (124.00 Byte)
Trainable params: 31 (124.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [35]:
model.get_weights()

[array([[-0.7737471 ,  0.12045801,  0.15428013],
        [ 0.3073662 , -0.44225025,  0.6865434 ],
        [-0.39560947,  0.4294687 , -0.02085721],
        [-0.32831275,  0.3764966 , -0.6530919 ],
        [ 0.268475  ,  0.02560312,  0.48852128]], dtype=float32),
 array([[ 0.36142087, -0.04181673,  0.9314645 ],
        [ 0.03862384,  0.99880767,  0.02985343],
        [ 0.93160236, -0.02518708, -0.3626052 ]], dtype=float32),
 array([0., 0., 0.], dtype=float32),
 array([[ 0.71032417],
        [-0.9422345 ],
        [-1.1523874 ]], dtype=float32),
 array([0.], dtype=float32)]

In [36]:
model.get_weights()[0].shape

(5, 3)

In [37]:
model.get_weights()[1].shape

(3, 3)

In [38]:
from keras.datasets import imdb

In [39]:
import numpy as np

(X_train,y_train),(X_test,y_test) = imdb.load_data()


In [40]:
len(X_train[0]) # this is going to be input size
#We want to take min length because in that case no padding will be required
#otherwise in case of max length padding will be required

218

In [41]:
for review in X_train:
  mylist.append(len(review))
min(mylist)

11

therefore i need padding

In [42]:
import numpy as np
sentence =[
    "india won worldcup",
    "rohit played very well",
    "above all is my imagination",
    "bharat mata ki jay",
    "definietly we goona win next worldcup"
]

In [43]:
from keras.preprocessing.text import Tokenizer

tokenizer means performing integer encoding

In [44]:
tokenizer = Tokenizer()

In [45]:
tokenizer.fit_on_texts(sentence)

In [46]:
tokenizer.word_index

{'worldcup': 1,
 'india': 2,
 'won': 3,
 'rohit': 4,
 'played': 5,
 'very': 6,
 'well': 7,
 'above': 8,
 'all': 9,
 'is': 10,
 'my': 11,
 'imagination': 12,
 'bharat': 13,
 'mata': 14,
 'ki': 15,
 'jay': 16,
 'definietly': 17,
 'we': 18,
 'goona': 19,
 'win': 20,
 'next': 21}

In [47]:
tokenizer.word_counts

OrderedDict([('india', 1),
             ('won', 1),
             ('worldcup', 2),
             ('rohit', 1),
             ('played', 1),
             ('very', 1),
             ('well', 1),
             ('above', 1),
             ('all', 1),
             ('is', 1),
             ('my', 1),
             ('imagination', 1),
             ('bharat', 1),
             ('mata', 1),
             ('ki', 1),
             ('jay', 1),
             ('definietly', 1),
             ('we', 1),
             ('goona', 1),
             ('win', 1),
             ('next', 1)])

In [48]:
tokenizer.document_count

5

In [49]:
encoding = tokenizer.texts_to_sequences(sentence)

we can do padding here also , means we want to make length of all sentence equal

In [50]:
from keras.utils import pad_sequences

In [51]:
pad_sequences(encoding, padding="post")

array([[ 2,  3,  1,  0,  0,  0],
       [ 4,  5,  6,  7,  0,  0],
       [ 8,  9, 10, 11, 12,  0],
       [13, 14, 15, 16,  0,  0],
       [17, 18, 19, 20, 21,  1]], dtype=int32)

in imdb dataset of keras we already get all things the integer coded

In [55]:
X_train = pad_sequences(X_train,padding="post",maxlen=50)
X_test = pad_sequences(X_test,padding="post",maxlen=50)

In [57]:
model = Sequential()
model.add(SimpleRNN(32,input_shape=(50,1)))

In [58]:
model.add(Dense(1,activation="sigmoid"))

In [60]:
model.summary()

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn_2 (SimpleRNN)    (None, 32)                1088      
                                                                 
 dense_2 (Dense)             (None, 1)                 33        
                                                                 
Total params: 1121 (4.38 KB)
Trainable params: 1121 (4.38 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [62]:
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

In [63]:
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=5)

Epoch 1/5
782/782 [==============================] - 17s 18ms/step - loss: 0.7318 - accuracy: 0.5061 - val_loss: 0.6934 - val_accuracy: 0.5044
Epoch 2/5
782/782 [==============================] - 12s 15ms/step - loss: 0.6929 - accuracy: 0.5056 - val_loss: 0.6935 - val_accuracy: 0.5045
Epoch 3/5
782/782 [==============================] - 12s 15ms/step - loss: 0.6927 - accuracy: 0.5097 - val_loss: 0.6950 - val_accuracy: 0.5050
Epoch 4/5
782/782 [==============================] - 14s 18ms/step - loss: 0.6927 - accuracy: 0.5056 - val_loss: 0.6945 - val_accuracy: 0.5033
Epoch 5/5
782/782 [==============================] - 11s 14ms/step - loss: 0.6926 - accuracy: 0.5094 - val_loss: 0.6935 - val_accuracy: 0.5026


In [64]:
model.predict(X_test)

782/782 [==============================] - 3s 4ms/step


array([[0.4983651 ],
       [0.49822205],
       [0.49822444],
       ...,
       [0.49822205],
       [0.49850586],
       [0.49822205]], dtype=float32)

In [66]:
Loss , accuracy = model.evaluate(X_test,y_test)

782/782 [==============================] - 4s 5ms/step - loss: 0.6935 - accuracy: 0.5026


In [67]:
Loss

0.6935423612594604

In [68]:
accuracy

0.5026000142097473